services:
  postgres:
    container_name: go_storage_pg
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - 'go-storage-pg-dev:/var/lib/postgresql/data'
  api:
    container_name: go_storage_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${API_PORT}:8080
    environment:
      - DB_SOURCE=${DB_SOURCE_CONTAINER}
    depends_on:
      - postgres
    tty: true
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:${POSTGRES_PORT}",
        "--",
        "/app/start.sh"
      ]
    volumes:
      - ./:/app
    command: [ "air" ]
  
volumes:
  go-storage-pg-dev:
