// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateFile(ctx context.Context, arg *CreateFileParams) (*File, error)
	CreateFiles(ctx context.Context, arg []*CreateFilesParams) (int64, error)
	DeleteFilesByNames(ctx context.Context, names []string) ([]*File, error)
	GetFileByName(ctx context.Context, name string) (*File, error)
	GetFileByNames(ctx context.Context, names []string) ([]*File, error)
	UpdateFile(ctx context.Context, arg *UpdateFileParams) (*File, error)
}

var _ Querier = (*Queries)(nil)
